### ISSUE TITLE
onShowed not being called

### ISSUE THREAD

**Issue by ManuelThomas** [jacklam718/react-native-popup-dialog#45] opened 2017-05-12 13:56 UTC
Could you please check: function from onShowed is not being called. I tried onDismiss and it is ok. here is my code:

```
<PopupDialog
              ref={(popupDialog) => { this.popupDialog = popupDialog; }}
              dialogAnimation = { new SlideAnimation({ slideFrom: 'bottom' }) }
              onShowed = {()=>{Alert.alert("asd","asd")
              console.log("hello")}}
              >
              <View style={{flexDirection: 'column'}}>
                <Text style={styles.popupTitle}>{this.state.popupTitle}</Text>
              </View>
</PopupDialog>
```

**Comment by jacklam718** [comment] 2017-05-13 04:21
@ManuelThomas 
The issue is fixed in version `0.7.28`. 
If any problems please let me know, thanks.
Thank you for report the issue!.

**Closed** 2017-05-13 04:22 UTC
